<?php session_start();

//CHECK IF THERE'S AN OPENED SESSION, IN THAT CASE, HEADER AGAIN TO THE CONTENT BECAUSE THE USER CAN TRY TO COPY THE ROUTE IN THE URL TO CREATE ANOTHER SESSION, OTHERWISE, IF THE USER TRYS TO GET TO THE CONTENT FROM THE LOG IN, HEADER TO THE LOGIN AND KILL THE PAGE EXECUTION.
if (isset($_SESSION['user'])) {
	require 'views/contenT.view.php';
} else {
	header('Location: login.php');
	die();
}

?>